name: neat
description: "A collection of utility functions and code generators that helps making neat flutter code"
version: 0.1.2
homepage: https://github.com/Pierre2tm/neat
repository: https://github.com/Pierre2tm/neat

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  neat_annotations: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1