name: neat_generator
description: "Neat package's code generator"
version: 0.2.0
homepage: https://github.com/Pierre2tm/neat
repository: https://github.com/Pierre2tm/neat

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.1.0
  build: ^2.1.1
  build_config: ^1.0.0
  code_builder: ^4.1.0
  collection: ^1.15.0
  dart_style: ^2.0.3
  source_gen: ^1.1.1
  neat_annotations: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.1.2